name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up swift packages
      run: swift package init --type library
    - name: Set up package for proj files
      run: swift package generate-xcodeproj   
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
